import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { GTWalsheim } from "@/lib/fonts";
import WalletProvider from "@/components/provider/WalletProvider";
import StateProvider from "@/components/provider/StateProvider";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/provider/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "font-sans antialiased bg-mantle-bg dark:bg-mantle-bg-dark",
          GTWalsheim.className
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <WalletProvider>
            <StateProvider>
              <div className="flex flex-col min-h-screen ">
                <Header />
                <main className="flex-1 w-full overflow-hidden">
                  {children}
                </main>
                <Footer />
              </div>
            </StateProvider>
          </WalletProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
